export enum SqlDataType {
  CHAR = 'char',
  VARCHAR = 'varchar',
  TEXT = 'text',
  TINYTEXT = 'tinytext',
  MEDIUMTEXT = 'mediumtext',
  LONGTEXT = 'longtext',
  TIME = 'time',
  GEOMETRY = 'geometry',
  SET = 'set',
  ENUM = 'enum',
  INTEGER = 'integer',
  INT = 'int',
  TINYINT = 'tinyint',
  SMALLINT = 'smallint',
  MEDIUMINT = 'mediumint',
  BIGINT = 'bigint',
  DOUBLE = 'double',
  DECIMAL = 'decimal',
  NUMERIC = 'numeric',
  FLOAT = 'float',
  YEAR = 'year',
  JSON = 'json',
  DATE = 'date',
  DATETIME = 'datetime',
  TIMESTAMP = 'timestamp',
  TINYBLOB = 'tinyblob',
  MEDIUMBLOB = 'mediumblob',
  LONGBLOB = 'longblob',
  BLOB = 'blob',
  BINARY = 'binary',
  VARBINARY = 'varbinary',
  BIT = 'bit'
}

export enum TsDataType {
  BOOLEAN = 'boolean',
  STRING = 'string',
  NUMBER = 'number',
  ARRAY = 'array',
  DATE = 'date',
  ENUM = 'enum',
  NULL = 'null'
}
